version: '3.8'
services:
  nats:
    image: nats:latest
    container_name: nats
    networks: 
      - yow
    command: ["-js", "-auth", "${NATS_TOKEN}"]
    # ports:
    #   - "4222:4222"
    #   - "8222:8222"
    env_file:
      - env/nats.env
    restart: 
      unless-stopped
  
  # yowbot: 
  #   image: zen:5000/yeoldwiz
  #   container_name: yowbot
  #   env_file:
  #     - env/yowapi.env
  #   networks:
  #     - yow
  #   depends_on:
  #     - nats
  #   restart: unless-stopped
  
  # yowcal:
  #   image: zen:5000/yeoldwiz
  #   container_name: yowcal
  #   env_file:
  #     - env/yowapi.env
  #   networks:
  #     - yow
  #   depends_on:
  #     - nats
  #   volumes:
  #     - cal45:/opt/yeoldwiz/calibrations
  #   command: ["sleep", "infinity"]
  
  yowapi:
    image: zen:5000/yowapi:latest
    container_name: yowapi
    environment:
      - MONGO_HOST=mongodb
      - GIN_MODE=debug
      - PORT=8443
    env_file:
      - env/nats.env
      - env/yowapi.env
    networks:
      - yow
      - mongonet
      - proxynet
    depends_on:
      - mongodb
      - nats
    restart: unless-stopped
    ports: 
      - 8443:8443


  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mongonet
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodb:/data/db
    restart: unless-stopped

networks: 
  yow: 
    external: true
  mongonet:
    external: true
  proxynet:
    external: true

volumes:
  cal45:
    external: true
  mongodb:
    external: true
